"""Postgres (Supabase) database initialization."""

import logging

from core.db import get_pool

logger = logging.getLogger(__name__)

# No migration framework exists — new fields on an existing entity must be a new table (CREATE TABLE IF NOT EXISTS is a no-op on an already-created table), never an ALTER TABLE or a column addition to an existing CREATE statement.
async def init_db():
    logger.info("Initializing Supabase (Postgres) schema...")
    pool = get_pool()
    async with pool.acquire() as db:
        await db.execute("""
            CREATE TABLE IF NOT EXISTS holdings_snapshot (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT UNIQUE,
                quantity INTEGER,
                average_price DOUBLE PRECISION,
                current_price DOUBLE PRECISION,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS watchlist (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT UNIQUE
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS ohlcv_cache (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT,
                date TEXT,
                open DOUBLE PRECISION,
                high DOUBLE PRECISION,
                low DOUBLE PRECISION,
                close DOUBLE PRECISION,
                volume BIGINT,
                UNIQUE(stock_code, date)
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT,
                rsi14 DOUBLE PRECISION,
                macd_line DOUBLE PRECISION,
                macd_signal DOUBLE PRECISION,
                sma50 DOUBLE PRECISION,
                sma200 DOUBLE PRECISION,
                pct_from_52w_high DOUBLE PRECISION,
                volume_ratio_20d DOUBLE PRECISION,
                composite_score DOUBLE PRECISION,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS job_heartbeats (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_name TEXT,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS session_tokens (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                token TEXT,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS refresh_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                requested_at TIMESTAMPTZ DEFAULT now(),
                processed_at TIMESTAMPTZ
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS stage_history (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT,
                date TEXT,
                stage INTEGER,
                sma_150 DOUBLE PRECISION,
                slope DOUBLE PRECISION,
                UNIQUE(stock_code, date)
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS stock_actions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT UNIQUE,
                action TEXT,
                rationale TEXT,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS ticker_mapping (
                stock_code TEXT PRIMARY KEY,
                nse_symbol TEXT,
                isin TEXT,
                resolved_at TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS backfill_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT,
                requested_at TIMESTAMPTZ DEFAULT now(),
                processed_at TIMESTAMPTZ,
                status TEXT,
                error TEXT
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS data_health (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                stock_code TEXT,
                source TEXT,
                status TEXT,
                message TEXT,
                timestamp TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS portfolio_value_history (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                timestamp TIMESTAMPTZ DEFAULT now(),
                total_invested DOUBLE PRECISION,
                total_current_value DOUBLE PRECISION,
                total_pnl DOUBLE PRECISION
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS stock_metadata (
                stock_code TEXT PRIMARY KEY,
                sector TEXT,
                industry TEXT,
                updated_at TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS sip_book (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL UNIQUE,
                stock_code TEXT,
                asset_category TEXT NOT NULL,
                monthly_sip DOUBLE PRECISION NOT NULL,
                execution_day INTEGER DEFAULT 31,
                status TEXT DEFAULT 'ACTIVE',
                quant_stage INTEGER DEFAULT 2,
                target_action TEXT DEFAULT 'CONTINUE',
                updated_at TIMESTAMPTZ DEFAULT now()
            )
        """)

        await db.execute("""
            CREATE TABLE IF NOT EXISTS dividend_schedule (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL,
                stock_code TEXT,
                asset_type TEXT NOT NULL,
                expected_dpu DOUBLE PRECISION NOT NULL,
                payout_frequency TEXT,
                last_ex_date TEXT,
                next_expected_payout TEXT,
                est_annual_cashflow DOUBLE PRECISION,
                yield_on_cost DOUBLE PRECISION,
                updated_at TIMESTAMPTZ DEFAULT now()
            )
        """)

    logger.info("Database tables initialized.")
