"""One-off schema setup for the Supabase (Postgres) migration.

Run via: docker compose run --rm bot python -m scripts.init_supabase_schema
Safe to rerun — every statement is CREATE TABLE IF NOT EXISTS.
"""

import asyncio
import logging
import socket

import asyncpg

from app_config import settings

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# NOTE: if DATABASE_URL's password contains a literal '@', it MUST be
# percent-encoded (%40) in .env. An unescaped '@' is otherwise ambiguous
# with the userinfo/host separator — Python's urlparse tolerates it (treats
# the last '@' as authoritative), but asyncpg's own DSN parser does not and
# silently extracts a malformed hostname, which then fails DNS resolution
# with a generic "Name or service not known" error that looks like a network
# problem rather than a DSN-parsing one. Cost real time to track down.

CONNECT_RETRIES = 3
CONNECT_RETRY_DELAY_SECONDS = 3


async def connect_with_retry(dsn):
    last_exc = None
    for attempt in range(1, CONNECT_RETRIES + 1):
        try:
            return await asyncpg.connect(dsn=dsn)
        except (socket.gaierror, OSError) as exc:
            last_exc = exc
            logger.warning(f"Connect attempt {attempt}/{CONNECT_RETRIES} failed ({exc}); retrying...")
            await asyncio.sleep(CONNECT_RETRY_DELAY_SECONDS)
    raise last_exc

SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS holdings_snapshot (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT UNIQUE,
        quantity INTEGER,
        average_price DOUBLE PRECISION,
        current_price DOUBLE PRECISION,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS watchlist (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT UNIQUE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ohlcv_cache (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT,
        date TEXT,
        open DOUBLE PRECISION,
        high DOUBLE PRECISION,
        low DOUBLE PRECISION,
        close DOUBLE PRECISION,
        volume BIGINT,
        UNIQUE (stock_code, date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS signals (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT,
        rsi14 DOUBLE PRECISION,
        macd_line DOUBLE PRECISION,
        macd_signal DOUBLE PRECISION,
        sma50 DOUBLE PRECISION,
        sma200 DOUBLE PRECISION,
        pct_from_52w_high DOUBLE PRECISION,
        volume_ratio_20d DOUBLE PRECISION,
        composite_score DOUBLE PRECISION,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS job_heartbeats (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_name TEXT,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS session_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token TEXT,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS refresh_requests (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        requested_at TIMESTAMPTZ DEFAULT now(),
        processed_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS stage_history (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT,
        date TEXT,
        stage INTEGER,
        sma_150 DOUBLE PRECISION,
        slope DOUBLE PRECISION,
        UNIQUE (stock_code, date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS stock_actions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT UNIQUE,
        action TEXT,
        rationale TEXT,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ticker_mapping (
        stock_code TEXT PRIMARY KEY,
        nse_symbol TEXT,
        isin TEXT,
        resolved_at TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS backfill_requests (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT,
        requested_at TIMESTAMPTZ DEFAULT now(),
        processed_at TIMESTAMPTZ,
        status TEXT,
        error TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS data_health (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stock_code TEXT,
        source TEXT,
        status TEXT,
        message TEXT,
        timestamp TIMESTAMPTZ DEFAULT now()
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolio_value_history (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp TIMESTAMPTZ DEFAULT now(),
        total_invested DOUBLE PRECISION,
        total_current_value DOUBLE PRECISION,
        total_pnl DOUBLE PRECISION
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS stock_metadata (
        stock_code TEXT PRIMARY KEY,
        sector TEXT,
        industry TEXT,
        updated_at TIMESTAMPTZ DEFAULT now()
    )
    """,
]


async def main():
    dsn = settings.database_url.get_secret_value()
    if not dsn:
        raise SystemExit("DATABASE_URL is not set in .env")

    logger.info("Connecting to Supabase...")
    conn = await connect_with_retry(dsn)
    try:
        for statement in SCHEMA_STATEMENTS:
            await conn.execute(statement)
        table_count = await conn.fetchval(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public'"
        )
        logger.info(f"Schema applied. {table_count} table(s) present in public schema.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
